version : '3'

services:
 dbservice:
  image: mysql:latest
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USERNAME = root
   #- MYSQL_USERNAME=root
  volumes:
   - ./data:/var/lib/mysql
   
  ports:
  - 3307:3306
  networks:
    - dummy

 appservice:
  build: ./
  depends_on:
    - dbservice
  environment:
    - spring.datasource.url=jdbc:mysql://dbservice:3306/springboot_schema?createDatabaseIfNotExist=true
    - spring.datasource.username=root
    - spring.datasource.password=root
  ports:
  - 8080:8080
  
  networks:
    - dummy
 
networks:
  dummy:
  
    